# Your Solution
version: '3'

services:

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sit722_sandara_user
      POSTGRES_PASSWORD: G1wuYwwPCbcjIlLJZpBZD9d5B4eNSbVY
      POSTGRES_DB: sit722_sandara
    restart: always

  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    image: sit722sandara.azurecr.io/book_catalog:latest
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sit722_sandara_user:G1wuYwwPCbcjIlLJZpBZD9d5B4eNSbVY@dpg-crpn8ct6l47c73am2i6g-a.oregon-postgres.render.com/sit722_sandara
    depends_on:
      - postgres
    restart: "no"
    platform: linux/amd64

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    image: sit722sandara.azurecr.io/inventory_management:latest
    container_name: inventory-management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://sit722_sandara_user:G1wuYwwPCbcjIlLJZpBZD9d5B4eNSbVY@dpg-crpn8ct6l47c73am2i6g-a.oregon-postgres.render.com/sit722_sandara
    depends_on:
      - postgres
    restart: "no"
    platform: linux/amd64
